{
    "name": "POSsible Personal Assistant",
    "summary": "Provider-independent operational backoffice foundation",
    "author": "POSsible",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "license": "LGPL-3",
    "depends": ["base", "mail", "contacts", "project"],
    "data": [
        "security/ppa_security.xml",
        "security/ir.model.access.csv",
        "data/ppa_source_data.xml",
        "data/ppa_activity_types.xml",
        "data/ppa_mailbox_cron.xml",
        "views/ppa_flow_views.xml",
        "views/ppa_mailbox_views.xml",
        "views/ppa_source_views.xml",
        "views/ppa_conversation_views.xml",
        "views/ppa_message_views.xml",
        "views/ppa_meeting_views.xml",
        "views/ppa_decision_views.xml",
        "views/ppa_suggested_action_views.xml",
        "views/ppa_ai_analysis_views.xml",
        "views/ppa_open_question_views.xml",
        "views/ppa_ingestion_event_views.xml",
        "views/ppa_menu.xml",
    ],
    "demo": ["demo/ppa_demo.xml"],
    "application": True,
    "installable": True,
}
