[options]
admin_passwd = change-me
db_host = ppa-db
db_port = 5432
db_user = odoo
db_password = change-me
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = False
list_db = True
log_level = info
