[options]
admin_passwd = change-me
db_host = ppa-db
db_port = 5432
db_user = odoo
db_password = change-me
db_name = ppa
dbfilter = ^ppa$
list_db = False
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = False
log_level = info
